name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.1
homepage: https://github.com/JacobWrenn/notus_to_html

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  notus: ^0.1.5

dev_dependencies:
  test:
